### ISSUE TITLE
SSH in R10K

### ISSUE THREAD

**Issue by BarnumD** [puppetlabs/puppet-in-docker#53]
Should the r10k image have ssh installed?  Currently if I try to clone a repo via git with ssh I get unknown command.

**Comment by bbgobie** [comment]
Agree with this

**Comment by stahnma** [comment]
Hey sorry for the very late response here. Could you give an example of the workflow is that you're doing? (I mean, I think the answer is yes it should have it installed, but I want to make sure I understand what the  problem is)

**Comment by BarnumD** [comment]
R10K should attach to our git server, pull the puppet code repo down (via ssh) and start it's task of building puppet environments from the code.  My assumption, for this docker based repo, is that r10k is a seprate container, and can communicate with puppet server (running in another container) to do what it does.

**Comment by kratan** [comment]
i admit, can you please include openssh-client into the image?

**Comment by underscorgan** [comment]
I can confirm that with the existing r10k image, running a `puppetfile install` currently fails with
```
ERROR    -> No Git providers are functional.
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/r10k-2.5.0/lib/r10k/git.rb:68:in `default_name'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/r10k-2.5.0/lib/r10k/git.rb:106:in `provider'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/r10k-2.5.0/lib/r10k/git.rb:114:in `cache'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/r10k-2.5.0/lib/r10k/git/stateful_repository.rb:25:in `initialize'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/r10k-2.5.0/lib/r10k/module/git.rb:26:in `new'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/r10k-2.5.0/lib/r10k/module/git.rb:26:in `initialize'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/r10k-2.5.0/lib/r10k/module.rb:26:in `new'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/r10k-2.5.0/lib/r10k/module.rb:26:in `new'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/r10k-2.5.0/lib/r10k/puppetfile.rb:94:in `add_module'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/r10k-2.5.0/lib/r10k/puppetfile.rb:176:in `mod'
/Puppetfile:27:in `load!'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/r10k-2.5.0/lib/r10k/puppetfile.rb:61:in `instance_eval'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/r10k-2.5.0/lib/r10k/puppetfile.rb:61:in `load!'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/r10k-2.5.0/lib/r10k/action/puppetfile/install.rb:23:in `visit_puppetfile'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/r10k-2.5.0/lib/r10k/action/visitor.rb:24:in `visit'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/r10k-2.5.0/lib/r10k/puppetfile.rb:130:in `accept'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/r10k-2.5.0/lib/r10k/action/puppetfile/install.rb:14:in `call'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/r10k-2.5.0/lib/r10k/action/runner.rb:33:in `call'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/r10k-2.5.0/lib/r10k/action/cri_runner.rb:67:in `call'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/cri-2.6.1/lib/cri/command_dsl.rb:223:in `block in runner'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/cri-2.6.1/lib/cri/command.rb:298:in `call'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/cri-2.6.1/lib/cri/command.rb:298:in `run_this'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/cri-2.6.1/lib/cri/command.rb:251:in `run'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/cri-2.6.1/lib/cri/command.rb:264:in `run'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/cri-2.6.1/lib/cri/command.rb:264:in `run'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/r10k-2.5.0/bin/r10k:7:in `<top (required)>'
/opt/puppetlabs/puppet/bin/r10k:23:in `load'
/opt/puppetlabs/puppet/bin/r10k:23:in `<main>'
```

and, adding openssh-client to the image I'm able to actually install based on a puppetfile.

I've opened #69 to get this fixed.
