### ISSUE TITLE
Standalone containers randomly failing

### ISSUE THREAD

**Issue by cohenaj194** [puppetlabs/puppet-in-docker#7]
When running several `puppet/puppetserver-standalone` containers and they will randomly fail one at a time with the following error message:

```
alecohen@master1-3113:~$ docker logs puppet1
Warning: The following options to parse-opts are unrecognized: :flag
2016-06-23 21:12:36,578 INFO  [o.e.j.u.log] Logging initialized @60634ms
2016-06-23 21:13:05,608 INFO  [p.s.v.versioned-code-service] No code-id-command set for versioned-code-service. Code-id will be nil.
2016-06-23 21:13:05,608 INFO  [p.s.v.versioned-code-service] No code-content-command set for versioned-code-service. Attempting to fetch code content will fail.
2016-06-23 21:13:05,609 INFO  [p.t.s.w.jetty9-service] Initializing web server(s).
2016-06-23 21:13:05,773 INFO  [p.s.j.jruby-puppet-service] Initializing the JRuby service
2016-06-23 21:13:05,774 WARN  [p.s.j.jruby-puppet-service] The 'jruby-puppet.use-legacy-auth-conf' setting is set to 'true'.  Support for the legacy Puppet auth.conf file is deprecated and will be removed in a future release.  Change this setting to 'false' and migrate your authorization rule definitions in the /etc/puppetlabs/puppet/auth.conf file to the /etc/puppetlabs/puppetserver/conf.d/auth.conf file.
2016-06-23 21:13:05,976 INFO  [p.s.j.jruby-puppet-internal] Creating JRuby instance with id 1.
2016-06-23 21:13:45,092 WARN  [puppetserver] Puppet Comparing Symbols to non-Symbol values is deprecated
   (file & line not available)
2016-06-23 21:13:45,236 INFO  [puppetserver] Puppet Puppet settings initialized; run mode: master
2016-06-23 21:33:06,031 ERROR [p.t.internal] Error during service init!!!
clojure.lang.ExceptionInfo: throw+: {:type :puppetlabs.services.jruby.jruby-puppet-service/jruby-timeout, :message "Attempt to borrow a JRuby instance from the pool timed out; Puppet Server is temporarily overloaded. If you get this error repeatedly, your server might be misconfigured or trying to serve too many agent nodes. Check Puppet Server settings: jruby-puppet.max-active-instances."}
	at puppetlabs.services.config.puppet_server_config_core$eval24611$get_puppet_config__24616$fn__24617$fn__24618.invoke(puppet_server_config_core.clj:107) ~[na:na]
	at puppetlabs.services.config.puppet_server_config_core$eval24611$get_puppet_config__24616$fn__24617.invoke(puppet_server_config_core.clj:107) ~[na:na]
	at puppetlabs.services.config.puppet_server_config_core$eval24611$get_puppet_config__24616.invoke(puppet_server_config_core.clj:102) ~[na:na]
	at puppetlabs.services.config.puppet_server_config_service$reify__24643$service_fnk__5299__auto___positional$reify__24654.init(puppet_server_config_service.clj:24) ~[na:na]
	at puppetlabs.trapperkeeper.services$eval5105$fn__5106$G__5093__5109.invoke(services.clj:8) ~[na:na]
	at puppetlabs.trapperkeeper.services$eval5105$fn__5106$G__5092__5113.invoke(services.clj:8) ~[na:na]
	at puppetlabs.trapperkeeper.internal$eval13828$run_lifecycle_fn_BANG___13835$fn__13836.invoke(internal.clj:177) ~[na:na]
	at puppetlabs.trapperkeeper.internal$eval13828$run_lifecycle_fn_BANG___13835.invoke(internal.clj:160) ~[na:na]
	at puppetlabs.trapperkeeper.internal$eval13857$run_lifecycle_fns__13862$fn__13863.invoke(internal.clj:211) ~[na:na]
	at puppetlabs.trapperkeeper.internal$eval13857$run_lifecycle_fns__13862.invoke(internal.clj:188) [na:na]
	at puppetlabs.trapperkeeper.internal$eval14328$build_app_STAR___14337$fn$reify__14347.init(internal.clj:561) [na:na]
	at puppetlabs.trapperkeeper.internal$eval14374$boot_services_for_app_STAR__STAR___14381$fn__14382$fn__14384.invoke(internal.clj:587) [na:na]
	at puppetlabs.trapperkeeper.internal$eval14374$boot_services_for_app_STAR__STAR___14381$fn__14382.invoke(internal.clj:586) [na:na]
	at puppetlabs.trapperkeeper.internal$eval14374$boot_services_for_app_STAR__STAR___14381.invoke(internal.clj:580) [na:na]
	at clojure.core$partial$fn__4529.invoke(core.clj:2499) [puppet-server-release.jar:na]
	at puppetlabs.trapperkeeper.internal$eval13896$initialize_lifecycle_worker__13907$fn__13908$fn__13995$state_machine__11872__auto____13996$fn__13998.invoke(internal.clj:228) [na:na]
	at puppetlabs.trapperkeeper.internal$eval13896$initialize_lifecycle_worker__13907$fn__13908$fn__13995$state_machine__11872__auto____13996.invoke(internal.clj:228) [na:na]
	at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:1011) [na:na]
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:1015) [na:na]
	at clojure.core.async$ioc_alts_BANG_$fn__12040.invoke(async.clj:378) [na:na]
	at clojure.core.async$do_alts$fn__11986$fn__11989.invoke(async.clj:247) [na:na]
	at clojure.core.async.impl.channels.ManyToManyChannel$fn__6807$fn__6808.invoke(channels.clj:95) [na:na]
	at clojure.lang.AFn.run(AFn.java:22) [puppet-server-release.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
2016-06-23 21:33:06,051 INFO  [p.t.internal] Beginning shutdown sequence
2016-06-23 21:40:02,126 INFO  [p.s.j.jruby-puppet-agents] Finished creating JRubyPuppet instance 1 of 1
2016-06-23 21:40:02,137 INFO  [p.s.j.jruby-puppet-agents] Flush request received; creating new JRuby pool.
2016-06-23 21:40:02,142 INFO  [p.s.j.jruby-puppet-agents] Replacing old JRuby pool with new instance.
2016-06-23 21:40:02,142 INFO  [p.s.j.jruby-puppet-agents] Swapped JRuby pools, beginning cleanup of old pool.
2016-06-23 21:40:02,151 INFO  [p.s.j.jruby-puppet-internal] Cleaned up old JRuby instance with id 1.
2016-06-23 21:40:02,154 INFO  [p.t.s.w.jetty9-service] Shutting down web server(s).
2016-06-23 21:40:02,163 INFO  [p.t.internal] Finished shutdown sequence
Exception in thread "main" clojure.lang.ExceptionInfo: throw+: {:type :puppetlabs.services.jruby.jruby-puppet-service/jruby-timeout, :message "Attempt to borrow a JRuby instance from the pool timed out; Puppet Server is temporarily overloaded. If you get this error repeatedly, your server might be misconfigured or trying to serve too many agent nodes. Check Puppet Server settings: jruby-puppet.max-active-instances."} {:type :puppetlabs.services.jruby.jruby-puppet-service/jruby-timeout, :message "Attempt to borrow a JRuby instance from the pool timed out; Puppet Server is temporarily overloaded. If you get this error repeatedly, your server might be misconfigured or trying to serve too many agent nodes. Check Puppet Server settings: jruby-puppet.max-active-instances."}
	at puppetlabs.services.config.puppet_server_config_core$eval24611$get_puppet_config__24616$fn__24617$fn__24618.invoke(puppet_server_config_core.clj:107)
	at puppetlabs.services.config.puppet_server_config_core$eval24611$get_puppet_config__24616$fn__24617.invoke(puppet_server_config_core.clj:107)
	at puppetlabs.services.config.puppet_server_config_core$eval24611$get_puppet_config__24616.invoke(puppet_server_config_core.clj:102)
	at puppetlabs.services.config.puppet_server_config_service$reify__24643$service_fnk__5299__auto___positional$reify__24654.init(puppet_server_config_service.clj:24)
	at puppetlabs.trapperkeeper.services$eval5105$fn__5106$G__5093__5109.invoke(services.clj:8)
	at puppetlabs.trapperkeeper.services$eval5105$fn__5106$G__5092__5113.invoke(services.clj:8)
	at puppetlabs.trapperkeeper.internal$eval13828$run_lifecycle_fn_BANG___13835$fn__13836.invoke(internal.clj:177)
	at puppetlabs.trapperkeeper.internal$eval13828$run_lifecycle_fn_BANG___13835.invoke(internal.clj:160)
	at puppetlabs.trapperkeeper.internal$eval13857$run_lifecycle_fns__13862$fn__13863.invoke(internal.clj:211)
	at puppetlabs.trapperkeeper.internal$eval13857$run_lifecycle_fns__13862.invoke(internal.clj:188)
	at puppetlabs.trapperkeeper.internal$eval14328$build_app_STAR___14337$fn$reify__14347.init(internal.clj:561)
	at puppetlabs.trapperkeeper.internal$eval14374$boot_services_for_app_STAR__STAR___14381$fn__14382$fn__14384.invoke(internal.clj:587)
	at puppetlabs.trapperkeeper.internal$eval14374$boot_services_for_app_STAR__STAR___14381$fn__14382.invoke(internal.clj:586)
	at puppetlabs.trapperkeeper.internal$eval14374$boot_services_for_app_STAR__STAR___14381.invoke(internal.clj:580)
	at clojure.core$partial$fn__4529.invoke(core.clj:2499)
	at puppetlabs.trapperkeeper.internal$eval13896$initialize_lifecycle_worker__13907$fn__13908$fn__13995$state_machine__11872__auto____13996$fn__13998.invoke(internal.clj:228)
	at puppetlabs.trapperkeeper.internal$eval13896$initialize_lifecycle_worker__13907$fn__13908$fn__13995$state_machine__11872__auto____13996.invoke(internal.clj:228)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:1011)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:1015)
	at clojure.core.async$ioc_alts_BANG_$fn__12040.invoke(async.clj:378)
	at clojure.core.async$do_alts$fn__11986$fn__11989.invoke(async.clj:247)
	at clojure.core.async.impl.channels.ManyToManyChannel$fn__6807$fn__6808.invoke(channels.clj:95)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I am running several containers here is my run command:

```
for i in `seq 1 5`; do
	docker run -d --name puppet$i --hostname puppet -P \
	-v /puppet-server:/etc/puppetlabs/code/ \
	puppet/puppetserver-standalone;
done
```

**Comment by garethr** [comment]
Puppet Server requires a decent amount of memory. My guess here is the machine you're running on is running out of resources. What size machine are you running this on? Do you see anything at the host level?

If you're familiar with Java you can pass PUPPETSERVER_JAVA_ARGS via environment variables to docker run to tweak the java args or allow for profiling.

Out of interest what's the rationale for running multiple instances of server?
